AllCops:
  NewCops: disable
  TargetRubyVersion: 3.1
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - .bundle/**/*
    - bin/**/*
    - vendor/**/*

Bundler/OrderedGems:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/IfUnlessModifier:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - spec/**/*_spec.rb

Layout/LineLength:
  Enabled: true
  Max: 120

Metrics/ModuleLength:
  Max: 120
  Exclude:
    - spec/**/*_spec.rb

Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Max: 25

Metrics/CyclomaticComplexity:
  Max: 12

Style/GlobalStdStream:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Lint/RedundantCopDisableDirective:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false
